### ISSUE TITLE
Visuels

### ISSUE THREAD

**Issue by epatrizio** [agile-france/site-Conf-Agile-France#1]
A voir JP :
- Visuel de fond
- Grand logo en haut à la droite de "La grande conférence Agile francophone"

**Comment by JeanPierreBONNAFOUS** [comment]
Je viens de cloner le site, tenter une modification sur 2 images et pousser ça sur GH (via "push originmaster" ) mais j'ai ce message là:

> remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
> remote: error: GH006: Protected branch update failed for refs/heads/master.
> remote: error: At least 1 approving review is required by reviewers with write access.
> To https://github.com/agile-france/site-Conf-Agile-France.git
> ! [remote rejected] master -> master (protected branch hook declined)
error: impossible de pousser des références vers 'https://github.com/agile-france/site-Conf-Agile-France.git'
Comprends pas grand chose mais on dirait qu'il faut qur QQ1 approuve.

**Comment by Frederic-ANDRE** [comment]
Il faut faire une branche de Dev


1. faire un Checkout de cette branche

1. 





1. 

1. 

-

**Comment by JeanPierreBONNAFOUS** [comment]
@epatrizio c'est quoi le grand logo AF en haut à droite qu'il faudrait refaire?

**Comment by epatrizio** [comment]
@JeanPierreBONNAFOUS 
il s'agit du grand logo AF en haut à droite à côté du titre "La grande conférence Agile francophone".
Il me semble que tu me disais avoir un visuel qui serait bien à cet endroit ...

**Comment by JeanPierreBONNAFOUS** [comment]
J'ai compris pourquoi le logo disparait... j'ai proposé une nouvelle version de la même taille que le téléphone. Vr RQ sur BaseCamp
