### ISSUE TITLE
Créer une page billetterie

### ISSUE THREAD

**Issue by epatrizio** [agile-france/site-Conf-Agile-France#11]
Page dédiée avec widget iframe
Accès depuis le menu

(en +, menu CFP)

**Comment by ismailnguyen** [comment]
Pull request en cours : https://github.com/agile-france/site-Conf-Agile-France/pull/14

**Comment by ismailnguyen** [comment]
PR mergé

**Comment by Musthuakqha** [comment]
@souvir
