### ISSUE TITLE
Optimiser les meta page par page 

### ISSUE THREAD

**Issue by Frederic-ANDRE** [agile-france/site-Conf-Agile-France#15]
Personnaliser page par page, à minima :

- <title>
- meta name="description"
- meta name="keywords"

**Comment by epatrizio** [comment]
Pour le coup, je l'ai fait de base : les meta sont bien différents sur chaque page et en accord avec le contenu.
Néanmoins, je n'ai clairement pas fait d'analyse de la concurrence, regardé les mots clefs populaires/pertinents dans les moteurs de recherche, etc. web market' stuff ;)

@Frederic-ANDRE as-tu plus en tête ?
A mon avis, on peut fermer cette issue ...
