### ISSUE TITLE
humanathon - ajouter un formulaire de contact

### ISSUE THREAD

**Issue by Frederic-ANDRE** [agile-france/site-Conf-Agile-France#5]
sur la page humanathon.html, il faudrait ajouter un formulaire de contact (en plus du lien vers l'email).
un peu comme sur le site de Laurent : https://www.awnb.org/humanathon

**Comment by epatrizio** [comment]
Dans l'état actuel des choses (site full static), le "mailto" html me semble être la seule solution.
On pourrait néanmoins ajouter un form, mais on conserverait un <form action:mailto >
ok @ismailnguyen and @souvir ?
A priori du moins, évitons d'avoir une dimension côté serveur ...

**Comment by Frederic-ANDRE** [comment]
je serai d'avis d'avoir un formulaire quand même, pour les gens pour qui le mailto ne marche pas ou qui n'ont pas envie.

**Comment by souvir** [comment]
Je comprend pas : s'ils n'ont pas envie d'envoyer un mail mais qui veulent envoyer un mail ?
Tant que le mail est écris et copiable alors même si le mailto marche pas ils peuvent envoyer un mail facilement

**Comment by epatrizio** [comment]
- Pas de form "classique" (pas côté serveur) > ajouter à côté du bouton les liens twitter et linkedin
- Intégrer chat slack
