### ISSUE TITLE
Changer texte : Attention, ouverture imminente CFP et billeterie !

### ISSUE THREAD

**Issue by Frederic-ANDRE** [agile-france/site-Conf-Agile-France#6]
Je trouve le "Attention" un peu agressif et "l'ouverture imminente CFP et billeterie !" un peu optimiste.

**Comment by epatrizio** [comment]
J'y pense, ce texte va sauter car nous lancerons le site en même temps que le CFP, au mieux ...
OK ? On ferme cette issue ?

**Comment by Frederic-ANDRE** [comment]
Nan c'est bien d'avoir un bandeau de message je trouve...
Le Attention sur fond rouge, je le garderai pour les message important plus tard : cloture du CFP, de la billetterie ...
Les message informatifs je les ferai en fond bleu ; on va ouvrir XXX, nouvelle rubrique...
Il faudrait un petit GIF animé ou un signalétique pour montrer que le message est nouveau (comme le badge dans le menu Humanathon

**Comment by epatrizio** [comment]
Que sur la home page 
- bande rouge > passage en bleue
- la rendre fixe au scroll
- 2 boutons CFP / billetterie "Proposez votre sujet" / "Achetez votre billet"
